name: Scrape Products

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  scrape:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.0'

      # Perbaikan utama di sini
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 playwright
          npx playwright install
    
      - name: Remove Existing grouped_products.json
        run: |
          if [ -f "grouped_products.json" ]; then
            rm grouped_products.json
          fi

      - name: Run Scrape Script
        run: |
          which playwright
          playwright --version
          python scrape.py

      # Pastikan menggunakan xvfb untuk mode headful jika diperlukan
      - name: Run with Xvfb (opsional)
        run: |
          xvfb-run --auto-servernum -- python scrape.py
        # Uncomment jika Anda membutuhkan mode headful

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add grouped_products.json
            git commit -m "Update grouped_products.json"
            git push https://${{ secrets.GH_TOKEN }}@github.com/JangOetama/AllyJastip.git HEAD:main
          fi
