name: Scrape Products

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Setiap hari pukul 00:00

jobs:
  scrape:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Remove Existing grouped_products.json (if exists)
        run: |
          if [ -f "grouped_products.json" ]; then
            echo "Removing existing grouped_products.json..."
            rm grouped_products.json
          else
            echo "No existing grouped_products.json found."
          fi

      - name: Run Scrape Script
        run: python scrape.py

      - name: Commit and Push Changes
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Periksa apakah ada perubahan (misalnya, file products.json baru dibuat)
          if [ -n "$(git status --porcelain)" ]; then
            echo "Changes detected. Committing and pushing changes..."
            git add .
            git commit -m "Update grouped_products.json"
            git push https://${{ secrets.GH_TOKEN }}@github.com/JangOetama/AllyJastip.git HEAD:main
          else
            echo "No changes to commit."
          fi
