name: Scrape Products (Cypress)

on:
  workflow_dispatch: # Manual trigger [[3]]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC [[4]]

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # [[1]]

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18 # Versi LTS Node.js

      - name: Install Dependencies
        run: npm install cypress string-similarity # Sesuai dependensi Cypress [[5]]

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6 # Action resmi Cypress [[8]]
        with:
          spec: cypress/e2e/scraping.spec.js
          browser: chrome
          headless: true
          config-file: false

      - name: Commit Results (if changed)
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Cek perubahan di direktori cypress/fixtures
          if [ -n "$(git status --porcelain cypress/fixtures/grouped_products.json)" ]; then
            echo "Menyimpan hasil scraping..."
            git add cypress/fixtures/grouped_products.json
            git commit -m "Update scraped products ($(date +'%Y-%m-%d %H:%M:%S'))"
            git push https://${GH_TOKEN}@github.com/JangOetama/AllyJastip.git HEAD:main
          else
            echo "Tidak ada perubahan yang perlu disimpan"
          fi
